# Generated by Django 5.0.2 on 2025-05-29 08:27

import ps_account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='document',
            field=models.FileField(upload_to=ps_account.models.get_document_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=ps_account.models.get_avatar_path),
        ),
    ]
