# Generated by Django 5.1 on 2024-10-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_account', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatars/baseavatar.jpg', upload_to='avatars/'),
        ),
    ]
