# Generated by Django 5.1 on 2024-10-03 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatgroup_users_in_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='is_private',
        ),
    ]
